"""Shared interfaces for agent-specific generated files."""

from typing import Protocol

from agent_safe.adapters.claude import ClaudeAdapter
from agent_safe.adapters.codex import CodexAdapter
from agent_safe.adapters.cursor import CursorAdapter
from agent_safe.models import AgentChoice, TemplateSpec


class AgentAdapter(Protocol):
    """Adapter that contributes generated files for one coding-agent surface."""

    def template_specs(self) -> tuple[TemplateSpec, ...]:
        """Return templates generated by this adapter."""
        ...


def adapters_for(agent: AgentChoice) -> tuple[AgentAdapter, ...]:
    """Return concrete adapters selected by an `agent-safe init` option."""
    if agent == "codex":
        return (CodexAdapter(),)
    if agent == "claude":
        return (ClaudeAdapter(),)
    if agent == "cursor":
        return (CursorAdapter(),)
    return (CodexAdapter(), ClaudeAdapter(), CursorAdapter())
