"""Regenerate generated agent instruction files."""

from dataclasses import dataclass
from pathlib import Path

from scaffold_guard import __version__
from scaffold_guard.manifest import MANIFEST_RELATIVE_PATH
from scaffold_guard.models import (
    AdapterSelection,
    AgentChoice,
    InitOptions,
    TemplateSpec,
    adapter_selection_for_agent,
)
from scaffold_guard.project_config import GeneratedProjectConfig, load_generated_project_config
from scaffold_guard.scaffold import (
    RenderedFile,
    package_template_specs,
    render_package_files,
)
from scaffold_guard.upgrade import UpgradeError, apply_upgrade_plan, plan_upgrade

GENERATED_MARKER_TEXT: str = (
    "generated by scaffold-guard; edit scaffold-guard.toml or rerun scaffold-guard compile-rules"
)
GENERATED_MARKER: str = f"<!-- {GENERATED_MARKER_TEXT} -->"


@dataclass(frozen=True, slots=True)
class CompileRulesSummary:
    """Summary of generated agent rule files."""

    target_dir: Path
    files: tuple[Path, ...]
    dry_run: bool

    def to_json(self) -> dict[str, object]:
        """Return a JSON-serializable summary."""
        return {
            "path": str(self.target_dir),
            "dry_run": self.dry_run,
            "files": [path.as_posix() for path in self.files],
        }


def compile_rules(
    root: Path,
    *,
    agent: AgentChoice | None,
    dry_run: bool,
    force: bool,
) -> CompileRulesSummary:
    """Regenerate agent instruction files from templates and project config."""
    config = load_generated_project_config(root)
    manifest_path = config.root / MANIFEST_RELATIVE_PATH
    if not manifest_path.exists() and not manifest_path.is_symlink():
        raise UpgradeError(
            "compile-rules requires a managed-file manifest; run `scaffold-guard upgrade` first."
        )
    if config.generated_with != __version__:
        raise UpgradeError(
            "compile-rules requires project metadata generated by the active ScaffoldGuard "
            f"version ({__version__}); preview and apply `scaffold-guard upgrade` first."
        )
    selected_adapters = _selected_adapters(config, agent)
    selected_agent = _agent_for_adapters(selected_adapters)
    options = _config_init_options(
        config,
        agent=selected_agent,
        adapters=selected_adapters,
        dry_run=dry_run,
        force=True,
    )
    rendered = tuple(file for file in render_package_files(options) if _is_agent_rendered(file))
    planned_files = tuple(file.path for file in rendered)
    plan = plan_upgrade(
        config.root,
        paths=planned_files,
        force=force,
        include_migrations=False,
    )
    if plan.conflicts:
        conflict_paths = ", ".join(action.path.as_posix() for action in plan.conflicts)
        msg = f"Refusing to overwrite changed generated file without --force: {conflict_paths}"
        raise UpgradeError(msg, kind="conflict")
    if not dry_run:
        apply_upgrade_plan(plan)
    return CompileRulesSummary(target_dir=config.root, files=planned_files, dry_run=dry_run)


def selected_agent_files(config: GeneratedProjectConfig) -> tuple[Path, ...]:
    """Return generated agent file paths selected by project config."""
    options = _config_init_options(
        config,
        agent=_agent_for_adapters(config.adapters),
        adapters=config.adapters,
        dry_run=True,
        force=False,
    )
    specs = package_template_specs(options)
    return tuple(
        Path(spec.destination.format(package_name=config.package))
        for spec in specs
        if _is_agent_spec(spec, package_name=config.package)
    )


def _selected_adapters(
    config: GeneratedProjectConfig,
    agent: AgentChoice | None,
) -> tuple[AdapterSelection, ...]:
    """Return the configured adapter scope requested by compile-rules."""
    if agent is None:
        return config.adapters
    requested = adapter_selection_for_agent(agent)
    unavailable = tuple(adapter for adapter in requested if adapter not in config.adapters)
    if unavailable:
        names = ", ".join(unavailable)
        raise UpgradeError(f"Requested adapters are not enabled in scaffold-guard.toml: {names}")
    return requested


def _config_init_options(
    config: GeneratedProjectConfig,
    *,
    agent: AgentChoice,
    adapters: tuple[AdapterSelection, ...],
    dry_run: bool,
    force: bool,
) -> InitOptions:
    """Build init options while preserving an exact adapter set."""
    return InitOptions(
        target_dir=config.root,
        project_slug=config.name,
        package_name=config.package,
        agent=agent,
        profile=config.profile,
        license="MIT",
        python_min=config.python_min,
        coverage=config.coverage_fail_under,
        ci=config.ci,
        docs_enabled=config.docs,
        dry_run=dry_run,
        force=force,
        ruff_enabled=config.ruff,
        mypy_enabled=config.mypy,
        pyright_enabled=config.pyright,
        ruff_mode=config.ruff_mode,
        python_typecheck_mode=config.python_typecheck_mode,
        python_typechecker=config.python_typechecker,
        typescript_strict_enabled=config.typescript_strict,
        biome_enabled=config.biome,
        vitest_enabled=config.vitest,
        adapter_selection=adapters,
    )


def _agent_for_adapters(adapters: tuple[AdapterSelection, ...]) -> AgentChoice:
    """Return the smallest render superset for an exact adapter set."""
    if adapters == ("codex",):
        return "codex"
    if adapters == ("claude",):
        return "claude"
    if adapters == ("cursor",):
        return "cursor"
    return "all"


def _is_agent_path(path: Path) -> bool:
    """Return whether a managed path belongs to shared or adapter instructions."""
    path_text = path.as_posix()
    return path_text in {"AGENTS.md", "CLAUDE.md"} or path_text.startswith(
        (".codex/", ".claude/", ".cursor/")
    )


def _is_agent_rendered(file: RenderedFile) -> bool:
    """Return whether a rendered managed file is in the compile-rules scope."""
    return file.lifecycle == "managed" and _is_agent_path(file.path)


def _is_agent_spec(spec: TemplateSpec, *, package_name: str) -> bool:
    """Return whether a managed template spec is in the compile-rules scope."""
    path = Path(spec.destination.format(package_name=package_name))
    return spec.lifecycle == "managed" and _is_agent_path(path)
