"""Regenerate generated agent instruction files."""

from dataclasses import dataclass, replace
from pathlib import Path

from scaffold_guard.models import AgentChoice, InitOptions
from scaffold_guard.project_config import GeneratedProjectConfig, load_generated_project_config
from scaffold_guard.scaffold import (
    RenderedFile,
    package_template_specs,
    render_package_files,
    write_rendered_files,
)

GENERATED_MARKER_TEXT: str = (
    "generated by scaffold-guard; edit scaffold-guard.toml or rerun scaffold-guard compile-rules"
)
GENERATED_MARKER: str = f"<!-- {GENERATED_MARKER_TEXT} -->"
GENERATED_COMMENT_MARKER: str = f"# {GENERATED_MARKER_TEXT}"
GENERATED_JSON_MARKER: str = "scaffold-guard generated"
AGENT_DESTINATIONS: frozenset[str] = frozenset(
    (
        "AGENTS.md",
        "CLAUDE.md",
        ".codex/config.toml",
        ".codex/hooks.json",
        ".codex/agents/implementation-worker.toml",
        ".codex/agents/docs-worker.toml",
        ".codex/agents/reviewer.toml",
        ".codex/hooks/workflow-evidence.sh",
        ".codex/rules/git.rules",
        ".codex/rules/validation.rules",
        ".claude/rules/python.md",
        ".claude/rules/typescript.md",
        ".claude/rules/testing.md",
        ".claude/rules/docs.md",
        ".claude/rules/security.md",
        ".claude/rules/git-hygiene.md",
        ".cursor/rules/python.mdc",
        ".cursor/rules/typescript.mdc",
        ".cursor/rules/testing.mdc",
        ".cursor/rules/docs.mdc",
        ".cursor/rules/security.mdc",
        ".cursor/rules/git-hygiene.mdc",
    )
)


@dataclass(frozen=True, slots=True)
class CompileRulesSummary:
    """Summary of generated agent rule files."""

    target_dir: Path
    files: tuple[Path, ...]
    dry_run: bool

    def to_json(self) -> dict[str, object]:
        """Return a JSON-serializable summary."""
        return {
            "path": str(self.target_dir),
            "dry_run": self.dry_run,
            "files": [path.as_posix() for path in self.files],
        }


def compile_rules(
    root: Path,
    *,
    agent: AgentChoice | None,
    dry_run: bool,
    force: bool,
) -> CompileRulesSummary:
    """Regenerate agent instruction files from templates and project config."""
    config = load_generated_project_config(root)
    selected_agent = agent or config.agent_choice
    options = config.to_init_options(dry_run=dry_run, force=True)
    options = _replace_agent(options, selected_agent)
    rendered = tuple(
        _with_generated_marker(file)
        for file in render_package_files(options)
        if file.path.as_posix() in AGENT_DESTINATIONS
    )

    if not force:
        _refuse_manual_files(config, rendered)

    planned_files = write_rendered_files(config.root, rendered, dry_run=dry_run, force=True)
    return CompileRulesSummary(target_dir=config.root, files=planned_files, dry_run=dry_run)


def selected_agent_files(config: GeneratedProjectConfig) -> tuple[Path, ...]:
    """Return generated agent file paths selected by project config."""
    specs = package_template_specs(config.to_init_options(dry_run=True, force=False))
    return tuple(
        Path(spec.destination.format(package_name=config.package))
        for spec in specs
        if spec.destination.format(package_name=config.package) in AGENT_DESTINATIONS
    )


def _replace_agent(options: InitOptions, agent: AgentChoice) -> InitOptions:
    """Return init options with a different selected agent."""
    return replace(options, agent=agent)


def _with_generated_marker(file: RenderedFile) -> RenderedFile:
    """Return a rendered file with a generated marker inserted."""
    content = file.content
    if _has_generated_marker(file.path, content):
        return file
    if file.path.suffix == ".mdc" and content.startswith("---\n"):
        second_delimiter = content.find("\n---\n", 4)
        if second_delimiter != -1:
            insert_at = second_delimiter + len("\n---\n")
            content = f"{content[:insert_at]}{GENERATED_MARKER}\n\n{content[insert_at:]}"
            return replace(file, content=content)
    if file.path.suffix in {".rules", ".toml", ".sh"}:
        content = f"{GENERATED_COMMENT_MARKER}\n\n{content}"
    elif file.path == Path(".codex/hooks.json"):
        return file
    elif not content.startswith(GENERATED_MARKER):
        content = f"{GENERATED_MARKER}\n\n{content}"
    return replace(file, content=content)


def _refuse_manual_files(
    config: GeneratedProjectConfig,
    rendered_files: tuple[RenderedFile, ...],
) -> None:
    """Refuse to overwrite existing rule files whose content changed."""
    for file in rendered_files:
        target = config.root / file.path
        if not target.exists():
            continue
        content = target.read_bytes()
        if content != file.content.encode("utf-8"):
            msg = f"Refusing to overwrite changed generated file without --force: {file.path}"
            raise FileExistsError(msg)


def _has_generated_marker(path: Path, content: str) -> bool:
    """Return whether content contains the generated marker for its file type."""
    if path.suffix in {".rules", ".toml", ".sh"}:
        return GENERATED_COMMENT_MARKER in content
    if path == Path(".codex/hooks.json"):
        return GENERATED_JSON_MARKER in content
    return GENERATED_MARKER in content
