"""Tests for scaffold file planning and writes."""

from pathlib import Path

import pytest

from scaffold_guard.models import AgentChoice, CiChoice, InitOptions, ProfileChoice
from scaffold_guard.renderer import TemplateRenderer
from scaffold_guard.scaffold import (
    RenderedFile,
    build_init_options,
    normalize_project_name,
    package_template_specs,
    render_file,
    render_package_files,
    scaffold_package_project,
    with_quality_tools,
    write_rendered_files,
)


def test_render_file_combines_template_and_destination() -> None:
    """A packaged template can become a rendered file model."""
    rendered_file = render_file(
        TemplateRenderer(),
        template_name="package/README.md.j2",
        destination="README.md",
        context={"project_slug": "demo", "package_name": "demo"},
    )

    assert rendered_file == RenderedFile(
        path=Path("README.md"),
        content=(
            "# demo\n\n"
            "Generated by `scaffold-guard`.\n\n"
            "## Quickstart\n\n"
            "```bash\n"
            "uv sync --all-groups\n"
            "scaffold-guard check\n"
            "scaffold-guard inspect-diff\n"
            "scaffold-guard validate\n"
            "```\n\n"
            "## Project Layout\n\n"
            "- `src/demo/` contains package source.\n"
            "- `tests/` contains unit and integration tests.\n"
            "- `docs/` contains MkDocs documentation.\n"
            "- `examples/` contains runnable examples.\n"
            "- `AGENTS.md` contains shared coding-agent instructions.\n"
        ),
    )


def test_normalize_project_name_converts_hyphen_to_package_underscore() -> None:
    """Project slugs and import package names are derived predictably."""
    assert normalize_project_name("Demo-Project") == ("demo-project", "demo_project")


@pytest.mark.parametrize(
    "name",
    ["", ".", "../escape", "/absolute", "nested/path", "bad-name!", "123demo", "class"],
)
def test_normalize_project_name_rejects_unsafe_or_invalid_names(name: str) -> None:
    """Unsafe names and invalid package identifiers fail before writes."""
    with pytest.raises(ValueError, match=r"Project name|Generated file path"):
        normalize_project_name(name)


def test_build_init_options_uses_current_base_directory(tmp_path: Path) -> None:
    """CLI inputs become a validated package scaffold configuration."""
    options = build_init_options(
        "demo-project",
        base_dir=tmp_path,
        agent="all",
        profile="python",
        license_name="MIT",
        python_min="3.13",
        coverage=95,
        ci="github",
        dry_run=False,
        force=False,
    )

    assert options.target_dir == tmp_path / "demo-project"
    assert options.project_slug == "demo-project"
    assert options.package_name == "demo_project"
    assert options.profile == "python"
    assert options.ruff_enabled
    assert options.mypy_enabled
    assert options.pyright_enabled


def test_build_init_options_accepts_legacy_package_profile(tmp_path: Path) -> None:
    """The old package profile input normalizes to the canonical Python profile."""
    options = build_init_options(
        "demo",
        base_dir=tmp_path,
        agent="all",
        profile="package",
        license_name="MIT",
        python_min="3.13",
        coverage=95,
        ci="github",
        dry_run=False,
        force=False,
    )

    assert options.profile == "python"
    assert options.docs_enabled
    assert options.python_enabled


def test_build_init_options_accepts_disabled_quality_tools(tmp_path: Path) -> None:
    """CLI tool selections are retained in scaffold options."""
    options = build_init_options(
        "demo",
        base_dir=tmp_path,
        agent="all",
        profile="python",
        license_name="MIT",
        python_min="3.13",
        coverage=95,
        ci="github",
        dry_run=False,
        force=False,
    )
    options = with_quality_tools(
        options,
        ruff=False,
        mypy=False,
        pyright=False,
        typescript_strict=False,
        biome=False,
        vitest=False,
    )

    assert not options.ruff_enabled
    assert not options.mypy_enabled
    assert not options.pyright_enabled
    assert not options.typescript_strict_enabled
    assert not options.biome_enabled
    assert not options.vitest_enabled


def test_build_init_options_can_target_current_directory(tmp_path: Path) -> None:
    """A dot target initializes the current directory using its name."""
    project_dir = tmp_path / "Current-Project"
    project_dir.mkdir()

    options = build_init_options(
        ".",
        base_dir=project_dir,
        agent="all",
        profile="python",
        license_name="MIT",
        python_min="3.13",
        coverage=95,
        ci="github",
        dry_run=False,
        force=False,
    )

    assert options.target_dir == project_dir
    assert options.project_slug == "current-project"
    assert options.package_name == "current_project"


def test_package_template_specs_include_selected_adapters(tmp_path: Path) -> None:
    """Adapter selections add their own generated files."""
    base_options = _init_options(tmp_path, agent="codex")
    all_options = _init_options(tmp_path, agent="all")

    codex_destinations = {spec.destination for spec in package_template_specs(base_options)}
    all_destinations = {spec.destination for spec in package_template_specs(all_options)}

    assert "AGENTS.md" in codex_destinations
    assert "CLAUDE.md" not in codex_destinations
    assert ".cursor/rules/python.mdc" not in codex_destinations
    assert "CLAUDE.md" in all_destinations
    assert ".claude/rules/python.md" in all_destinations
    assert ".cursor/rules/python.mdc" in all_destinations


def test_typescript_template_specs_filter_python_adapter_rules(tmp_path: Path) -> None:
    """TypeScript-only scaffolds generate TypeScript adapter rules without Python rules."""
    options = _init_options(tmp_path, agent="all", profile="typescript")

    destinations = {spec.destination for spec in package_template_specs(options)}

    assert "package.json" in destinations
    assert "tsconfig.json" in destinations
    assert ".claude/rules/typescript.md" in destinations
    assert ".cursor/rules/typescript.mdc" in destinations
    assert ".claude/rules/python.md" not in destinations
    assert ".cursor/rules/python.mdc" not in destinations
    assert "pyproject.toml" not in destinations


def test_typescript_template_specs_omit_disabled_optional_tool_files(tmp_path: Path) -> None:
    """Disabled TypeScript tools remove their generated config and test files."""
    options = _init_options(
        tmp_path,
        agent="codex",
        profile="typescript",
        typescript_tools=(False, False),
    )

    destinations = {spec.destination for spec in package_template_specs(options)}

    assert "biome.json" not in destinations
    assert "vitest.config.ts" not in destinations
    assert "tests/index.test.ts" not in destinations
    assert "tsconfig.json" in destinations
    assert "package.json" in destinations


def test_monorepo_template_specs_include_python_and_typescript_rules(tmp_path: Path) -> None:
    """Monorepo scaffolds include both Python and TypeScript adapter guidance."""
    options = _init_options(tmp_path, agent="all", profile="monorepo")

    destinations = {spec.destination for spec in package_template_specs(options)}

    assert "pyproject.toml" in destinations
    assert "package.json" in destinations
    assert "packages/python/src/{package_name}/core.py" in destinations
    assert "packages/typescript/src/index.ts" in destinations
    assert ".claude/rules/python.md" in destinations
    assert ".claude/rules/typescript.md" in destinations
    assert ".cursor/rules/python.mdc" in destinations
    assert ".cursor/rules/typescript.mdc" in destinations


def test_monorepo_template_specs_omit_disabled_typescript_tool_files(tmp_path: Path) -> None:
    """Disabled monorepo TypeScript tools remove optional config and tests."""
    options = _init_options(
        tmp_path,
        agent="codex",
        profile="monorepo",
        typescript_tools=(False, False),
    )

    destinations = {spec.destination for spec in package_template_specs(options)}

    assert "biome.json" not in destinations
    assert "packages/typescript/vitest.config.ts" not in destinations
    assert "packages/typescript/tests/index.test.ts" not in destinations
    assert "packages/typescript/tsconfig.json" in destinations
    assert "packages/typescript/package.json" in destinations


def test_package_template_specs_omit_pyright_config_when_disabled(tmp_path: Path) -> None:
    """Pyright-specific config is only generated when Pyright is enabled."""
    options = _init_options(tmp_path, agent="codex", pyright=False)

    destinations = {spec.destination for spec in package_template_specs(options)}

    assert "pyrightconfig.json" not in destinations


def test_package_template_specs_include_selected_ci_provider(tmp_path: Path) -> None:
    """CI provider selection controls generated workflow files."""
    github_options = _init_options(tmp_path, agent="codex", ci="github")
    gitlab_options = _init_options(tmp_path, agent="codex", ci="gitlab")

    github_destinations = {spec.destination for spec in package_template_specs(github_options)}
    gitlab_destinations = {spec.destination for spec in package_template_specs(gitlab_options)}

    assert ".github/workflows/ci.yml" in github_destinations
    assert ".github/workflows/docs.yml" in github_destinations
    assert ".gitlab-ci.yml" not in github_destinations
    assert ".gitlab-ci.yml" in gitlab_destinations
    assert ".github/workflows/ci.yml" not in gitlab_destinations
    assert ".github/workflows/docs.yml" not in gitlab_destinations


def test_render_package_files_has_no_project_jinja_placeholders(tmp_path: Path) -> None:
    """Package rendering resolves project-specific Jinja placeholders."""
    rendered_files = render_package_files(_init_options(tmp_path, agent="all"))

    for rendered_file in rendered_files:
        assert "{{ project_" not in rendered_file.content
        assert "{{ package_" not in rendered_file.content
        assert "{%" not in rendered_file.content


def test_scaffold_package_project_allows_existing_empty_target(tmp_path: Path) -> None:
    """The high-level init path can write into an existing empty directory."""
    target_dir = tmp_path / "demo"
    target_dir.mkdir()

    summary = scaffold_package_project(_init_options(tmp_path, agent="codex"))

    assert summary.target_dir == target_dir
    assert (target_dir / "AGENTS.md").exists()


def test_scaffold_package_project_rejects_non_empty_target_without_force(tmp_path: Path) -> None:
    """The high-level init path refuses populated target directories unless forced."""
    target_dir = tmp_path / "demo"
    target_dir.mkdir()
    (target_dir / "notes.txt").write_text("keep\n", encoding="utf-8")

    with pytest.raises(FileExistsError, match="not empty"):
        scaffold_package_project(_init_options(tmp_path, agent="codex"))


def test_scaffold_package_project_preserves_extra_files_with_force(tmp_path: Path) -> None:
    """Forced init overwrites generated files without deleting unrelated files."""
    target_dir = tmp_path / "demo"
    target_dir.mkdir()
    notes = target_dir / "notes.txt"
    notes.write_text("keep\n", encoding="utf-8")
    (target_dir / "README.md").write_text("old\n", encoding="utf-8")

    summary = scaffold_package_project(_init_options(tmp_path, agent="codex", force=True))

    assert Path("README.md") in summary.files
    assert "Generated by `scaffold-guard`" in (target_dir / "README.md").read_text(encoding="utf-8")
    assert notes.read_text(encoding="utf-8") == "keep\n"


def test_scaffold_package_project_dry_run_does_not_create_target(tmp_path: Path) -> None:
    """The high-level dry-run returns planned files without writing."""
    summary = scaffold_package_project(_init_options(tmp_path, agent="codex", dry_run=True))

    assert summary.dry_run
    assert Path("AGENTS.md") in summary.files
    assert not (tmp_path / "demo").exists()


def test_write_rendered_files_dry_run_does_not_touch_filesystem(tmp_path: Path) -> None:
    """Dry-run returns planned files without creating the target directory."""
    target_dir = tmp_path / "demo"
    planned = write_rendered_files(
        target_dir,
        [RenderedFile(path=Path("README.md"), content="# Demo\n")],
        dry_run=True,
        force=False,
    )

    assert planned == (Path("README.md"),)
    assert not target_dir.exists()


def test_write_rendered_files_writes_inside_target_directory(tmp_path: Path) -> None:
    """Rendered files are written below the requested target root."""
    target_dir = tmp_path / "demo"

    planned = write_rendered_files(
        target_dir,
        [RenderedFile(path=Path("docs/index.md"), content="# Docs\n")],
        dry_run=False,
        force=False,
    )

    assert planned == (Path("docs/index.md"),)
    assert (target_dir / "docs" / "index.md").read_text(encoding="utf-8") == "# Docs\n"


def test_write_rendered_files_rejects_file_as_target_directory(tmp_path: Path) -> None:
    """The target root must be a directory when it already exists."""
    target_file = tmp_path / "demo"
    target_file.write_text("not a directory\n", encoding="utf-8")

    with pytest.raises(NotADirectoryError, match="not a directory"):
        write_rendered_files(
            target_file,
            [RenderedFile(path=Path("README.md"), content="new\n")],
            dry_run=False,
            force=False,
        )


@pytest.mark.parametrize("unsafe_path", [Path("../escape.md"), Path.cwd() / "escape.md"])
def test_write_rendered_files_rejects_paths_that_escape_target(
    tmp_path: Path,
    unsafe_path: Path,
) -> None:
    """Scaffold writes reject generated paths that could escape the target."""
    with pytest.raises(ValueError, match=r"Generated file path|outside target"):
        write_rendered_files(
            tmp_path / "demo",
            [RenderedFile(path=unsafe_path, content="escape\n")],
            dry_run=False,
            force=False,
        )


def test_write_rendered_files_rejects_symlinked_parent_escape(tmp_path: Path) -> None:
    """A generated path cannot escape through a symlinked parent directory."""
    target_dir = tmp_path / "demo"
    outside_dir = tmp_path / "outside"
    target_dir.mkdir()
    outside_dir.mkdir()
    (target_dir / "linked").symlink_to(outside_dir, target_is_directory=True)

    with pytest.raises(ValueError, match="outside target directory"):
        write_rendered_files(
            target_dir,
            [RenderedFile(path=Path("linked/escape.md"), content="escape\n")],
            dry_run=False,
            force=False,
        )

    assert not (outside_dir / "escape.md").exists()


def test_write_rendered_files_preserves_existing_files_without_force(tmp_path: Path) -> None:
    """Existing generated destinations are not overwritten by default."""
    target_dir = tmp_path / "demo"
    existing = target_dir / "README.md"
    existing.parent.mkdir(parents=True)
    existing.write_text("existing\n", encoding="utf-8")

    with pytest.raises(FileExistsError):
        write_rendered_files(
            target_dir,
            [RenderedFile(path=Path("README.md"), content="new\n")],
            dry_run=False,
            force=False,
        )

    assert existing.read_text(encoding="utf-8") == "existing\n"


def test_write_rendered_files_overwrites_existing_files_with_force(tmp_path: Path) -> None:
    """The force flag intentionally overwrites existing generated destinations."""
    target_dir = tmp_path / "demo"
    existing = target_dir / "README.md"
    existing.parent.mkdir(parents=True)
    existing.write_text("existing\n", encoding="utf-8")

    write_rendered_files(
        target_dir,
        [RenderedFile(path=Path("README.md"), content="new\n")],
        dry_run=False,
        force=True,
    )

    assert existing.read_text(encoding="utf-8") == "new\n"


def _init_options(
    tmp_path: Path,
    *,
    agent: AgentChoice,
    ci: CiChoice = "github",
    dry_run: bool = False,
    force: bool = False,
    profile: ProfileChoice = "python",
    ruff: bool = True,
    mypy: bool = True,
    pyright: bool = True,
    typescript_tools: tuple[bool, bool] = (True, True),
) -> InitOptions:
    """Build standard test init options."""
    options = build_init_options(
        "demo",
        base_dir=tmp_path,
        agent=agent,
        profile=profile,
        license_name="MIT",
        python_min="3.13",
        coverage=95,
        ci=ci,
        dry_run=dry_run,
        force=force,
    )
    return with_quality_tools(
        options,
        ruff=ruff,
        mypy=mypy,
        pyright=pyright,
        biome=typescript_tools[0],
        vitest=typescript_tools[1],
    )
