"""Tests for scaffold file planning and writes."""

import asyncio
import json
import os
import shlex
from dataclasses import replace
from pathlib import Path

import pytest

from scaffold_guard.manifest import load_manifest
from scaffold_guard.models import (
    AdapterSelection,
    AgentChoice,
    CiChoice,
    InitOptions,
    ProfileChoice,
    TemplateLifecycle,
)
from scaffold_guard.renderer import TemplateRenderer
from scaffold_guard.scaffold import (
    RenderedFile,
    build_init_options,
    build_project_manifest,
    normalize_project_name,
    package_template_specs,
    render_file,
    render_package_files,
    scaffold_package_project,
    with_quality_tools,
    write_rendered_files,
)
from scaffold_guard.versions import GENERATED_PROJECT_MINIMUM_VERSION

MINIMUM_FORBIDDEN_GIT_RULES = 5
EXACT_ADAPTER_SELECTIONS: tuple[tuple[AdapterSelection, ...], ...] = (
    (),
    ("codex",),
    ("claude",),
    ("cursor",),
    ("codex", "claude"),
    ("codex", "cursor"),
    ("claude", "cursor"),
    ("codex", "claude", "cursor"),
)


def test_render_file_combines_template_and_destination() -> None:
    """A packaged template can become a rendered file model."""
    rendered_file = render_file(
        TemplateRenderer(),
        template_name="package/README.md.j2",
        destination="README.md",
        template_id="package/README.md",
        lifecycle="seed",
        context={"project_slug": "demo", "package_name": "demo"},
    )

    assert rendered_file == RenderedFile(
        path=Path("README.md"),
        content=(
            "# demo\n\n"
            "Generated by `scaffold-guard`.\n\n"
            "## Quickstart\n\n"
            "```bash\n"
            "uv sync --all-groups\n"
            "scaffold-guard check\n"
            "scaffold-guard inspect-diff\n"
            "scaffold-guard validate\n"
            "```\n\n"
            "## Project Layout\n\n"
            "- `src/demo/` contains package source.\n"
            "- `tests/` contains unit and integration tests.\n"
            "- `docs/` contains MkDocs documentation.\n"
            "- `examples/` contains runnable examples.\n"
            "- `AGENTS.md` contains shared coding-agent instructions.\n"
        ),
        template_id="package/README.md",
        lifecycle="seed",
    )


def test_normalize_project_name_converts_hyphen_to_package_underscore() -> None:
    """Project slugs and import package names are derived predictably."""
    assert normalize_project_name("Demo-Project") == ("demo-project", "demo_project")


@pytest.mark.parametrize(
    "name",
    ["", ".", "../escape", "/absolute", "nested/path", "bad-name!", "123demo", "class"],
)
def test_normalize_project_name_rejects_unsafe_or_invalid_names(name: str) -> None:
    """Unsafe names and invalid package identifiers fail before writes."""
    with pytest.raises(ValueError, match=r"Project name|Generated file path"):
        normalize_project_name(name)


def test_build_init_options_uses_current_base_directory(tmp_path: Path) -> None:
    """CLI inputs become a validated package scaffold configuration."""
    options = build_init_options(
        "demo-project",
        base_dir=tmp_path,
        agent="all",
        profile="python",
        license_name="MIT",
        python_min="3.13",
        coverage=95,
        ci="github",
        dry_run=False,
        force=False,
    )

    assert options.target_dir == tmp_path / "demo-project"
    assert options.project_slug == "demo-project"
    assert options.package_name == "demo_project"
    assert options.profile == "python"
    assert options.ruff_enabled
    assert options.mypy_enabled
    assert options.pyright_enabled


def test_build_init_options_accepts_legacy_package_profile(tmp_path: Path) -> None:
    """The old package profile input normalizes to the canonical Python profile."""
    options = build_init_options(
        "demo",
        base_dir=tmp_path,
        agent="all",
        profile="package",
        license_name="MIT",
        python_min="3.13",
        coverage=95,
        ci="github",
        dry_run=False,
        force=False,
    )

    assert options.profile == "python"
    assert options.docs_enabled
    assert options.python_enabled


def test_build_init_options_accepts_disabled_quality_tools(tmp_path: Path) -> None:
    """CLI tool selections are retained in scaffold options."""
    options = build_init_options(
        "demo",
        base_dir=tmp_path,
        agent="all",
        profile="python",
        license_name="MIT",
        python_min="3.13",
        coverage=95,
        ci="github",
        dry_run=False,
        force=False,
    )
    options = with_quality_tools(
        options,
        ruff=False,
        mypy=False,
        pyright=False,
        typescript_strict=False,
        biome=False,
        vitest=False,
    )

    assert not options.ruff_enabled
    assert not options.mypy_enabled
    assert not options.pyright_enabled
    assert not options.typescript_strict_enabled
    assert not options.biome_enabled
    assert not options.vitest_enabled


def test_build_init_options_can_target_current_directory(tmp_path: Path) -> None:
    """A dot target initializes the current directory using its name."""
    project_dir = tmp_path / "Current-Project"
    project_dir.mkdir()

    options = build_init_options(
        ".",
        base_dir=project_dir,
        agent="all",
        profile="python",
        license_name="MIT",
        python_min="3.13",
        coverage=95,
        ci="github",
        dry_run=False,
        force=False,
    )

    assert options.target_dir == project_dir
    assert options.project_slug == "current-project"
    assert options.package_name == "current_project"


def test_package_template_specs_include_selected_adapters(tmp_path: Path) -> None:
    """Adapter selections add their own generated files."""
    base_options = _init_options(tmp_path, agent="codex")
    all_options = _init_options(tmp_path, agent="all")

    codex_destinations = {spec.destination for spec in package_template_specs(base_options)}
    all_destinations = {spec.destination for spec in package_template_specs(all_options)}

    assert "AGENTS.md" in codex_destinations
    assert ".codex/config.toml" in codex_destinations
    assert ".codex/hooks.json" in codex_destinations
    assert ".codex/agents/implementation-worker.toml" in codex_destinations
    assert ".codex/agents/docs-worker.toml" in codex_destinations
    assert ".codex/agents/reviewer.toml" in codex_destinations
    assert ".codex/hooks/workflow-evidence.sh" in codex_destinations
    assert ".codex/rules/git.rules" in codex_destinations
    assert ".codex/rules/validation.rules" in codex_destinations
    assert "CLAUDE.md" not in codex_destinations
    assert ".cursor/rules/python.mdc" not in codex_destinations
    assert ".codex/config.toml" in all_destinations
    assert "CLAUDE.md" in all_destinations
    assert ".claude/rules/python.md" in all_destinations
    assert ".cursor/rules/python.mdc" in all_destinations


def test_template_specs_carry_stable_ids_and_lifecycle(tmp_path: Path) -> None:
    """Planned templates include stable manifest identifiers and lifecycle data."""
    options = _init_options(tmp_path, agent="all")

    specs_by_destination = {spec.destination: spec for spec in package_template_specs(options)}

    assert specs_by_destination["AGENTS.md"].template_id == "package/AGENTS.md"
    assert specs_by_destination["AGENTS.md"].lifecycle == "managed"
    assert specs_by_destination[".github/workflows/ci.yml"].lifecycle == "managed"
    assert specs_by_destination[".codex/config.toml"].lifecycle == "managed"
    assert specs_by_destination["pyproject.toml"].lifecycle == "structured"
    assert specs_by_destination["scaffold-guard.toml"].lifecycle == "structured"
    assert specs_by_destination["pyrightconfig.json"].lifecycle == "structured"
    assert specs_by_destination[".gitignore"].lifecycle == "seed"
    assert specs_by_destination["src/{package_name}/core.py"].lifecycle == "seed"


@pytest.mark.parametrize(
    ("selection", "expected", "excluded"),
    [
        (
            ("codex", "claude"),
            {".codex/config.toml", "CLAUDE.md"},
            {".cursor/rules/python.mdc"},
        ),
        (
            ("codex", "cursor"),
            {".codex/config.toml", ".cursor/rules/python.mdc"},
            {"CLAUDE.md"},
        ),
        (
            ("claude", "cursor"),
            {"CLAUDE.md", ".cursor/rules/python.mdc"},
            {".codex/config.toml"},
        ),
    ],
)
def test_package_template_specs_use_exact_adapter_selection(
    tmp_path: Path,
    selection: tuple[AdapterSelection, ...],
    expected: set[str],
    excluded: set[str],
) -> None:
    """Scaffold planning honors exact adapter combinations beyond CLI shorthand."""
    options = replace(_init_options(tmp_path, agent="codex"), adapter_selection=selection)

    destinations = {spec.destination for spec in package_template_specs(options)}

    assert expected <= destinations
    assert destinations.isdisjoint(excluded)


def test_package_template_specs_preserve_empty_adapter_selection(tmp_path: Path) -> None:
    """Config-driven rendering can omit every optional adapter file."""
    options = replace(_init_options(tmp_path, agent="codex"), adapter_selection=())

    destinations = {spec.destination for spec in package_template_specs(options)}
    rendered_files = render_package_files(options)
    manifest = build_project_manifest(options, rendered_files)

    assert "AGENTS.md" in destinations
    assert ".codex/config.toml" not in destinations
    assert "CLAUDE.md" not in destinations
    assert ".cursor/rules/python.mdc" not in destinations
    assert manifest.adapters == ()


def test_lifecycle_catalog_is_complete_for_supported_generation_matrix(tmp_path: Path) -> None:
    """Every rendered catalog has stable unique identifiers and lifecycle coverage."""
    for profile in ("minimal", "python", "typescript", "monorepo"):
        for ci in ("github", "gitlab"):
            for adapter_selection in EXACT_ADAPTER_SELECTIONS:
                for ruff, mypy, pyright, typescript_tools in _tool_matrix(profile):
                    options = _init_options(
                        tmp_path,
                        agent="codex",
                        ci=ci,
                        profile=profile,
                        ruff=ruff,
                        mypy=mypy,
                        pyright=pyright,
                        typescript_tools=typescript_tools,
                    )
                    options = replace(options, adapter_selection=adapter_selection)

                    specs = package_template_specs(options)
                    destinations = [spec.destination for spec in specs]
                    template_ids = [spec.template_id for spec in specs]
                    lifecycles = {spec.lifecycle for spec in specs}

                    assert all(template_ids)
                    assert lifecycles <= {"managed", "structured", "seed"}
                    assert len(destinations) == len(set(destinations))
                    assert len(template_ids) == len(set(template_ids))
                    assert {"managed", "structured", "seed"} <= lifecycles


def test_typescript_template_specs_filter_python_adapter_rules(tmp_path: Path) -> None:
    """TypeScript-only scaffolds generate TypeScript adapter rules without Python rules."""
    options = _init_options(tmp_path, agent="all", profile="typescript")

    destinations = {spec.destination for spec in package_template_specs(options)}

    assert "package.json" in destinations
    assert "tsconfig.json" in destinations
    assert ".claude/rules/typescript.md" in destinations
    assert ".cursor/rules/typescript.mdc" in destinations
    assert ".codex/rules/validation.rules" in destinations
    assert ".claude/rules/python.md" not in destinations
    assert ".cursor/rules/python.mdc" not in destinations
    assert "pyproject.toml" in destinations


def test_typescript_template_specs_omit_disabled_optional_tool_files(tmp_path: Path) -> None:
    """Disabled TypeScript tools remove their generated config and test files."""
    options = _init_options(
        tmp_path,
        agent="codex",
        profile="typescript",
        typescript_tools=(False, False),
    )

    destinations = {spec.destination for spec in package_template_specs(options)}

    assert "biome.json" not in destinations
    assert "vitest.config.ts" not in destinations
    assert "tests/index.test.ts" not in destinations
    assert "tsconfig.json" in destinations
    assert "package.json" in destinations


def test_monorepo_template_specs_include_python_and_typescript_rules(tmp_path: Path) -> None:
    """Monorepo scaffolds include both Python and TypeScript adapter guidance."""
    options = _init_options(tmp_path, agent="all", profile="monorepo")

    destinations = {spec.destination for spec in package_template_specs(options)}

    assert "pyproject.toml" in destinations
    assert "package.json" in destinations
    assert "packages/python/src/{package_name}/core.py" in destinations
    assert "packages/typescript/src/index.ts" in destinations
    assert ".claude/rules/python.md" in destinations
    assert ".claude/rules/typescript.md" in destinations
    assert ".cursor/rules/python.mdc" in destinations
    assert ".cursor/rules/typescript.mdc" in destinations
    assert ".codex/rules/validation.rules" in destinations


def test_monorepo_template_specs_omit_disabled_typescript_tool_files(tmp_path: Path) -> None:
    """Disabled monorepo TypeScript tools remove optional config and tests."""
    options = _init_options(
        tmp_path,
        agent="codex",
        profile="monorepo",
        typescript_tools=(False, False),
    )

    destinations = {spec.destination for spec in package_template_specs(options)}

    assert "biome.json" not in destinations
    assert "packages/typescript/vitest.config.ts" not in destinations
    assert "packages/typescript/tests/index.test.ts" not in destinations
    assert "packages/typescript/tsconfig.json" in destinations
    assert "packages/typescript/package.json" in destinations


def test_package_template_specs_omit_pyright_config_when_disabled(tmp_path: Path) -> None:
    """Pyright-specific config is only generated when Pyright is enabled."""
    options = _init_options(tmp_path, agent="codex", pyright=False)

    destinations = {spec.destination for spec in package_template_specs(options)}

    assert "pyrightconfig.json" not in destinations


def test_package_template_specs_include_selected_ci_provider(tmp_path: Path) -> None:
    """CI provider selection controls generated workflow files."""
    github_options = _init_options(tmp_path, agent="codex", ci="github")
    gitlab_options = _init_options(tmp_path, agent="codex", ci="gitlab")

    github_destinations = {spec.destination for spec in package_template_specs(github_options)}
    gitlab_destinations = {spec.destination for spec in package_template_specs(gitlab_options)}

    assert ".github/workflows/ci.yml" in github_destinations
    assert ".github/workflows/docs.yml" in github_destinations
    assert ".gitlab-ci.yml" not in github_destinations
    assert ".gitlab-ci.yml" in gitlab_destinations
    assert ".github/workflows/ci.yml" not in gitlab_destinations
    assert ".github/workflows/docs.yml" not in gitlab_destinations


def test_render_package_files_has_no_project_jinja_placeholders(tmp_path: Path) -> None:
    """Package rendering resolves project-specific Jinja placeholders."""
    rendered_files = render_package_files(_init_options(tmp_path, agent="all"))

    for rendered_file in rendered_files:
        assert "{{ project_" not in rendered_file.content
        assert "{{ package_" not in rendered_file.content
        assert "{%" not in rendered_file.content


def test_render_package_files_derives_python_tool_versions_from_python_min(
    tmp_path: Path,
) -> None:
    """Python tool config follows the selected minimum Python version."""
    options = replace(_init_options(tmp_path, agent="codex"), python_min="3.14")
    rendered_files = render_package_files(options)
    rendered_by_path = {rendered_file.path: rendered_file for rendered_file in rendered_files}
    pyproject = rendered_by_path[Path("pyproject.toml")].content

    assert 'requires-python = ">=3.14"' in pyproject
    assert 'target-version = "py314"' in pyproject
    assert 'python_version = "3.14"' in pyproject


def test_render_package_files_renders_codex_hooks_and_profile_rules(tmp_path: Path) -> None:
    """Codex adapter files are deterministic and profile-aware."""
    rendered_files = render_package_files(
        _init_options(tmp_path, agent="codex", profile="monorepo")
    )
    rendered_by_path = {rendered_file.path: rendered_file for rendered_file in rendered_files}
    config = rendered_by_path[Path(".codex/config.toml")].content
    hooks = rendered_by_path[Path(".codex/hooks.json")].content
    hook_payload = json.loads(hooks)
    git_rules = rendered_by_path[Path(".codex/rules/git.rules")].content
    pyproject = rendered_by_path[Path("pyproject.toml")].content
    rules = rendered_by_path[Path(".codex/rules/validation.rules")].content
    implementation_worker = rendered_by_path[
        Path(".codex/agents/implementation-worker.toml")
    ].content
    docs_worker = rendered_by_path[Path(".codex/agents/docs-worker.toml")].content
    reviewer = rendered_by_path[Path(".codex/agents/reviewer.toml")].content
    evidence_hook = rendered_by_path[Path(".codex/hooks/workflow-evidence.sh")].content

    assert "hooks = true" in config
    assert "multi_agent = true" in config
    assert "[agents]" in config
    assert "max_threads = 4" in config
    assert "max_depth = 1" in config
    assert '"PostToolUse"' in hooks
    assert "SubagentStart" in hook_payload["hooks"]
    assert "SubagentStop" in hook_payload["hooks"]
    assert "Stop" in hook_payload["hooks"]
    assert "workflow-evidence.sh" in hooks
    assert "git rev-parse --show-toplevel" in hooks
    assert 'scaffold-guard.toml\\" ]; do root=' in hooks
    assert 'scaffold-guard check --path \\"$root\\"' in hooks
    assert 'name = "implementation-worker"' in implementation_worker
    assert "Own only the files, modules, templates, or tests explicitly assigned" in (
        implementation_worker
    )
    assert 'name = "docs-worker"' in docs_worker
    assert "never document aspirational behavior as current" in docs_worker
    assert 'name = "reviewer"' in reviewer
    assert 'sandbox_mode = "read-only"' in reviewer
    assert "Do not claim final task completion" in reviewer
    assert "workflow evidence warning" in evidence_hook
    assert "exit 0" in evidence_hook
    assert 'pattern = ["git", "commit"]' in git_rules
    assert 'pattern = ["git", "push"]' in git_rules
    assert 'pattern = ["uv", "run", "scaffold-guard", "publish"]' in git_rules
    assert 'pattern = ["scaffold-guard", "publish"]' not in git_rules
    assert 'decision = "prompt"' not in git_rules
    assert git_rules.count('decision = "forbidden"') >= MINIMUM_FORBIDDEN_GIT_RULES
    assert 'decision = "allow"' in git_rules
    assert f'"scaffold-guard>={GENERATED_PROJECT_MINIMUM_VERSION}"' in pyproject
    assert 'pattern = ["uv", "run", "ruff", "check", "packages/python"]' in rules
    assert 'pattern = ["npm", "run", "ts:typecheck"]' in rules


def test_codex_workflow_evidence_hook_records_warning_only_jsonl(tmp_path: Path) -> None:
    """The generated workflow evidence hook records local JSONL and exits successfully."""
    project_dir = tmp_path / "demo"
    project_dir.mkdir()
    (project_dir / "scaffold-guard.toml").write_text('[project]\nname = "demo"\n', encoding="utf-8")
    log_path = tmp_path / "evidence.jsonl"
    rendered_files = render_package_files(_init_options(tmp_path, agent="codex"))
    hook_content = next(
        file.content
        for file in rendered_files
        if file.path == Path(".codex/hooks/workflow-evidence.sh")
    )
    hook_path = tmp_path / "workflow-evidence.sh"
    hook_path.write_text(hook_content, encoding="utf-8")
    env = os.environ.copy()
    env["CODEX_WORKFLOW_EVIDENCE_LOG"] = str(log_path)

    stdout = asyncio.run(
        _run_command_stdout(
            f"/bin/sh {hook_path} post-tool-use {project_dir} edit",
            cwd=project_dir,
            env=env,
        )
    )
    payload = json.loads(log_path.read_text(encoding="utf-8"))

    assert stdout == ""
    assert payload["source"] == "codex-hook"
    assert payload["event"] == "post-tool-use"
    assert payload["subject"] == "edit"
    assert payload["root"] == str(project_dir)
    assert payload["changed_files"] == 0


def test_codex_workflow_evidence_hook_warns_when_edits_lack_subagent(
    tmp_path: Path,
) -> None:
    """The stop hook warns when edits occurred without subagent evidence."""
    project_dir = tmp_path / "demo"
    project_dir.mkdir()
    (project_dir / "scaffold-guard.toml").write_text('[project]\nname = "demo"\n', encoding="utf-8")
    log_path = tmp_path / "evidence.jsonl"
    state_path = Path(f"{log_path}.state")
    rendered_files = render_package_files(_init_options(tmp_path, agent="codex"))
    hook_content = next(
        file.content
        for file in rendered_files
        if file.path == Path(".codex/hooks/workflow-evidence.sh")
    )
    hook_path = tmp_path / "workflow-evidence.sh"
    hook_path.write_text(hook_content, encoding="utf-8")
    env = os.environ.copy()
    env["CODEX_WORKFLOW_EVIDENCE_LOG"] = str(log_path)

    asyncio.run(
        _run_command(
            f"/bin/sh {hook_path} post-tool-use {project_dir} edit",
            cwd=project_dir,
            env=env,
        )
    )
    stdout, stderr = asyncio.run(
        _run_command(f"/bin/sh {hook_path} stop {project_dir} turn", cwd=project_dir, env=env)
    )
    records = [
        json.loads(line)
        for line in log_path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]

    assert stdout == ""
    assert "no SubagentStart evidence was recorded" in stderr
    assert not state_path.exists()
    assert [record["event"] for record in records] == ["post-tool-use", "stop"]


def test_codex_hook_command_resolves_non_git_subdirectory_root(tmp_path: Path) -> None:
    """The generated hook command climbs to project root when git is unavailable."""
    project_dir = tmp_path / "demo"
    subdir = project_dir / "src"
    fake_bin = tmp_path / "bin"
    subdir.mkdir(parents=True)
    fake_bin.mkdir()
    (project_dir / "scaffold-guard.toml").write_text('[project]\nname = "demo"\n', encoding="utf-8")
    fake_scaffold_guard = fake_bin / "scaffold-guard"
    fake_scaffold_guard.write_text("#!/bin/sh\nprintf '%s\\n' \"$@\"\n", encoding="utf-8")
    fake_scaffold_guard.chmod(0o755)

    rendered_files = render_package_files(_init_options(tmp_path, agent="codex"))
    hooks = next(file.content for file in rendered_files if file.path == Path(".codex/hooks.json"))
    hook_payload = json.loads(hooks)
    hook_command = hook_payload["hooks"]["PostToolUse"][0]["hooks"][0]["command"]
    env = os.environ.copy()
    env["PATH"] = f"{fake_bin}{os.pathsep}{env.get('PATH', '')}"

    stdout = asyncio.run(_run_command_stdout(hook_command, cwd=subdir, env=env))

    assert stdout.splitlines() == ["check", "--path", str(project_dir)]


def test_render_package_files_rejects_invalid_python_min_for_ruff_target(
    tmp_path: Path,
) -> None:
    """Ruff target-version normalization requires a major.minor Python version."""
    options = replace(_init_options(tmp_path, agent="codex"), python_min="3.14.0")

    with pytest.raises(ValueError, match=r"major\.minor"):
        render_package_files(options)


def test_scaffold_package_project_allows_existing_empty_target(tmp_path: Path) -> None:
    """The high-level init path can write into an existing empty directory."""
    target_dir = tmp_path / "demo"
    target_dir.mkdir()

    summary = scaffold_package_project(_init_options(tmp_path, agent="codex"))

    assert summary.target_dir == target_dir
    assert (target_dir / "AGENTS.md").exists()


def test_scaffold_package_project_allows_unrelated_existing_files(tmp_path: Path) -> None:
    """The high-level init path preserves unrelated existing files."""
    target_dir = tmp_path / "demo"
    target_dir.mkdir()
    notes = target_dir / "notes.txt"
    notes.write_text("keep\n", encoding="utf-8")

    summary = scaffold_package_project(_init_options(tmp_path, agent="codex"))

    assert Path("AGENTS.md") in summary.files
    assert (target_dir / "AGENTS.md").exists()
    assert notes.read_text(encoding="utf-8") == "keep\n"


def test_scaffold_package_project_rejects_existing_generated_destination(
    tmp_path: Path,
) -> None:
    """Generated destination conflicts require explicit force before any writes."""
    target_dir = tmp_path / "demo"
    target_dir.mkdir()
    (target_dir / "README.md").write_text("old\n", encoding="utf-8")

    with pytest.raises(FileExistsError, match="would generate"):
        scaffold_package_project(_init_options(tmp_path, agent="codex"))

    assert not (target_dir / "AGENTS.md").exists()


def test_scaffold_package_project_preserves_extra_files_with_force(tmp_path: Path) -> None:
    """Forced init overwrites generated files without deleting unrelated files."""
    target_dir = tmp_path / "demo"
    target_dir.mkdir()
    notes = target_dir / "notes.txt"
    notes.write_text("keep\n", encoding="utf-8")
    (target_dir / "README.md").write_text("old\n", encoding="utf-8")

    summary = scaffold_package_project(_init_options(tmp_path, agent="codex", force=True))

    assert Path("README.md") in summary.files
    assert "Generated by `scaffold-guard`" in (target_dir / "README.md").read_text(encoding="utf-8")
    assert notes.read_text(encoding="utf-8") == "keep\n"


def test_scaffold_package_project_dry_run_does_not_create_target(tmp_path: Path) -> None:
    """The high-level dry-run returns planned files without writing."""
    summary = scaffold_package_project(_init_options(tmp_path, agent="codex", dry_run=True))

    assert summary.dry_run
    assert Path("AGENTS.md") in summary.files
    assert Path(".scaffold-guard/manifest.json") in summary.files
    assert not (tmp_path / "demo").exists()


def test_scaffold_package_project_writes_manifest(tmp_path: Path) -> None:
    """Init writes managed-file metadata for the rendered scaffold."""
    target_dir = tmp_path / "demo"

    summary = scaffold_package_project(_init_options(tmp_path, agent="codex"))

    assert Path(".scaffold-guard/manifest.json") in summary.files
    manifest = load_manifest(target_dir / ".scaffold-guard/manifest.json")
    files = {file.path: file for file in manifest.files}
    assert manifest.profile == "python"
    assert manifest.adapters == ("codex",)
    assert manifest.generated_with
    assert manifest.requires_scaffold_guard.startswith(">=")
    assert files["AGENTS.md"].template_id == "package/AGENTS.md"
    assert files["AGENTS.md"].sha256
    assert "pyproject.toml" not in files
    assert "src/demo/core.py" not in files
    assert ".scaffold-guard/manifest.json" not in files


def test_scaffold_package_project_rejects_existing_manifest_before_writes(tmp_path: Path) -> None:
    """The manifest participates in generated destination conflict preflight."""
    target_dir = tmp_path / "demo"
    manifest_path = target_dir / ".scaffold-guard" / "manifest.json"
    manifest_path.parent.mkdir(parents=True)
    manifest_path.write_text("old\n", encoding="utf-8")

    with pytest.raises(FileExistsError, match=r"manifest\.json"):
        scaffold_package_project(_init_options(tmp_path, agent="codex"))

    assert not (target_dir / "AGENTS.md").exists()


def test_scaffold_package_project_rejects_symlinked_manifest_before_writes(
    tmp_path: Path,
) -> None:
    """A symlinked manifest path fails during preflight before other files are written."""
    target_dir = tmp_path / "demo"
    manifest_path = target_dir / ".scaffold-guard" / "manifest.json"
    manifest_path.parent.mkdir(parents=True)
    manifest_path.symlink_to(tmp_path / "missing-manifest.json")

    with pytest.raises(FileExistsError, match=r"manifest\.json"):
        scaffold_package_project(_init_options(tmp_path, agent="codex"))

    assert not (target_dir / "AGENTS.md").exists()


def test_scaffold_package_project_rejects_symlinked_manifest_parent_before_writes(
    tmp_path: Path,
) -> None:
    """A symlinked destination parent is rejected even when it resolves inside root."""
    target_dir = tmp_path / "demo"
    real_metadata_dir = target_dir / "real-metadata"
    symlinked_metadata_dir = target_dir / ".scaffold-guard"
    real_metadata_dir.mkdir(parents=True)
    symlinked_metadata_dir.symlink_to(real_metadata_dir, target_is_directory=True)

    with pytest.raises(FileExistsError, match=r"symbolic link"):
        scaffold_package_project(_init_options(tmp_path, agent="codex"))

    assert not (target_dir / "AGENTS.md").exists()


def test_build_project_manifest_sorts_managed_paths_and_hashes_content(tmp_path: Path) -> None:
    """Manifest entries are deterministic and exclude non-managed rendered files."""
    options = replace(
        _init_options(tmp_path, agent="codex"),
        adapter_selection=("codex", "claude"),
    )
    manifest = build_project_manifest(
        options,
        (
            _rendered_file("b.txt", "second\n", lifecycle="seed"),
            _rendered_file("a.txt", "first\n", lifecycle="managed"),
            _rendered_file("c.toml", "structured\n", lifecycle="structured"),
        ),
    )

    assert [file.path for file in manifest.files] == ["a.txt"]
    assert manifest.adapters == ("codex", "claude")
    assert manifest.files[0].sha256


def test_write_rendered_files_dry_run_does_not_touch_filesystem(tmp_path: Path) -> None:
    """Dry-run returns planned files without creating the target directory."""
    target_dir = tmp_path / "demo"
    planned = write_rendered_files(
        target_dir,
        [_rendered_file("README.md", "# Demo\n")],
        dry_run=True,
        force=False,
    )

    assert planned == (Path("README.md"),)
    assert not target_dir.exists()


def test_write_rendered_files_writes_inside_target_directory(tmp_path: Path) -> None:
    """Rendered files are written below the requested target root."""
    target_dir = tmp_path / "demo"

    planned = write_rendered_files(
        target_dir,
        [_rendered_file("docs/index.md", "# Docs\n")],
        dry_run=False,
        force=False,
    )

    assert planned == (Path("docs/index.md"),)
    assert (target_dir / "docs" / "index.md").read_text(encoding="utf-8") == "# Docs\n"


def test_write_rendered_files_rejects_file_as_target_directory(tmp_path: Path) -> None:
    """The target root must be a directory when it already exists."""
    target_file = tmp_path / "demo"
    target_file.write_text("not a directory\n", encoding="utf-8")

    with pytest.raises(NotADirectoryError, match="not a directory"):
        write_rendered_files(
            target_file,
            [_rendered_file("README.md", "new\n")],
            dry_run=False,
            force=False,
        )


@pytest.mark.parametrize("unsafe_path", [Path("../escape.md"), Path.cwd() / "escape.md"])
def test_write_rendered_files_rejects_paths_that_escape_target(
    tmp_path: Path,
    unsafe_path: Path,
) -> None:
    """Scaffold writes reject generated paths that could escape the target."""
    with pytest.raises(ValueError, match=r"Generated file path|outside target"):
        write_rendered_files(
            tmp_path / "demo",
            [
                RenderedFile(
                    path=unsafe_path,
                    content="escape\n",
                    template_id="test/escape",
                    lifecycle="seed",
                )
            ],
            dry_run=False,
            force=False,
        )


def test_write_rendered_files_rejects_symlinked_parent_escape(tmp_path: Path) -> None:
    """A generated path cannot escape through a symlinked parent directory."""
    target_dir = tmp_path / "demo"
    outside_dir = tmp_path / "outside"
    target_dir.mkdir()
    outside_dir.mkdir()
    (target_dir / "linked").symlink_to(outside_dir, target_is_directory=True)

    with pytest.raises(FileExistsError, match="symbolic link"):
        write_rendered_files(
            target_dir,
            [_rendered_file("linked/escape.md", "escape\n")],
            dry_run=False,
            force=False,
        )

    assert not (outside_dir / "escape.md").exists()


def test_write_rendered_files_preserves_existing_files_without_force(tmp_path: Path) -> None:
    """Existing generated destinations are not overwritten by default."""
    target_dir = tmp_path / "demo"
    existing = target_dir / "README.md"
    existing.parent.mkdir(parents=True)
    existing.write_text("existing\n", encoding="utf-8")

    with pytest.raises(FileExistsError):
        write_rendered_files(
            target_dir,
            [_rendered_file("README.md", "new\n")],
            dry_run=False,
            force=False,
        )

    assert existing.read_text(encoding="utf-8") == "existing\n"


def test_write_rendered_files_overwrites_existing_files_with_force(tmp_path: Path) -> None:
    """The force flag intentionally overwrites existing generated destinations."""
    target_dir = tmp_path / "demo"
    existing = target_dir / "README.md"
    existing.parent.mkdir(parents=True)
    existing.write_text("existing\n", encoding="utf-8")

    write_rendered_files(
        target_dir,
        [_rendered_file("README.md", "new\n")],
        dry_run=False,
        force=True,
    )

    assert existing.read_text(encoding="utf-8") == "new\n"


def _rendered_file(
    path: str,
    content: str,
    *,
    lifecycle: TemplateLifecycle = "seed",
) -> RenderedFile:
    """Build a rendered file fixture with stable lifecycle metadata."""
    return RenderedFile(
        path=Path(path),
        content=content,
        template_id=f"test/{path}",
        lifecycle=lifecycle,
    )


def _init_options(
    tmp_path: Path,
    *,
    agent: AgentChoice,
    ci: CiChoice = "github",
    dry_run: bool = False,
    force: bool = False,
    profile: ProfileChoice = "python",
    ruff: bool = True,
    mypy: bool = True,
    pyright: bool = True,
    typescript_tools: tuple[bool, bool] = (True, True),
) -> InitOptions:
    """Build standard test init options."""
    options = build_init_options(
        "demo",
        base_dir=tmp_path,
        agent=agent,
        profile=profile,
        license_name="MIT",
        python_min="3.13",
        coverage=95,
        ci=ci,
        dry_run=dry_run,
        force=force,
    )
    return with_quality_tools(
        options,
        ruff=ruff,
        mypy=mypy,
        pyright=pyright,
        biome=typescript_tools[0],
        vitest=typescript_tools[1],
    )


def _tool_matrix(
    profile: ProfileChoice,
) -> tuple[tuple[bool, bool, bool, tuple[bool, bool]], ...]:
    """Return relevant optional tool combinations for one generated profile."""
    python_tool_sets = ((True, True, True), (False, False, False))
    typescript_tool_sets = ((True, True), (False, False))
    if profile == "minimal":
        return ((True, True, True, (True, True)),)
    if profile == "python":
        return tuple((*python_tools, (True, True)) for python_tools in python_tool_sets)
    if profile == "typescript":
        return tuple((True, True, True, ts_tools) for ts_tools in typescript_tool_sets)
    return tuple(
        (*python_tools, ts_tools)
        for python_tools in python_tool_sets
        for ts_tools in typescript_tool_sets
    )


async def _run_command_stdout(command: str, *, cwd: Path, env: dict[str, str]) -> str:
    """Run a generated shell command and return stdout."""
    stdout, _stderr = await _run_command(command, cwd=cwd, env=env)
    return stdout


async def _run_command(command: str, *, cwd: Path, env: dict[str, str]) -> tuple[str, str]:
    """Run a generated shell command and return stdout plus stderr."""
    process = await asyncio.create_subprocess_exec(
        *shlex.split(command),
        cwd=cwd,
        env=env,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await process.communicate()
    assert process.returncode == 0, stderr.decode("utf-8", errors="replace")
    return stdout.decode("utf-8", errors="replace"), stderr.decode("utf-8", errors="replace")
